### ISSUE TITLE
Timed until does not seem to work

### ISSUE THREAD

**Issue by sokolsky** [mvcisback/py-metric-temporal-logic#215]
I cannot get timed until to work.  I try:

d2 = { 
  'a': [(0,True),(1,True),(3,True),(4,True),(5,False),(6,True)],
  'b': [(0,False), (3,True)]
}
f2 = mtl.parse('(a U[0,3] b)')
print(f2(d2,quantitative=False))

The formula parses correctly, but evaluation throws an exception:
--------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sokolsky/.local/lib/python3.6/site-packages/mtl/ast.py", line 47, in _eval
    return evaluator.pointwise_sat(exp, dt)(trace, time, quantitative)
  File "/home/sokolsky/.local/lib/python3.6/site-packages/mtl/evaluator.py", line 69, in _eval_mtl
    t = f(sig).items()[0][0]
  File "/home/sokolsky/.local/lib/python3.6/site-packages/mtl/evaluator.py", line 87, in _eval
    sigs = [f(x) for f in fs]
  File "/home/sokolsky/.local/lib/python3.6/site-packages/mtl/evaluator.py", line 87, in <listcomp>
    sigs = [f(x) for f in fs]
  File "/home/sokolsky/.local/lib/python3.6/site-packages/mtl/evaluator.py", line 128, in _eval
    return f(x).rolling(a, b).map(_min, tag=phi)
  File "/home/sokolsky/.local/lib/python3.6/site-packages/discrete_signals/signals.py", line 101, in map
    data = fn.walk_values(func, list(self.items()))
  File "/home/sokolsky/.local/lib/python3.6/site-packages/funcy/colls.py", line 159, in walk_values
    return _factory(coll, mapper=f)(xmap(pair_f, iteritems(coll)))
  File "/home/sokolsky/.local/lib/python3.6/site-packages/funcy/colls.py", line 157, in pair_f
    return k, f(v)
  File "/home/sokolsky/.local/lib/python3.6/site-packages/mtl/evaluator.py", line 125, in _min
    return min(val[phi.arg])
KeyError: ((a W b) & ~G~b)
-----------------------------

The untimed until works as expected, also timed always works fine.  I tried several variants of the formula and the data.  Nothing works and the error seems the same.  Please help!

**Comment by mvcisback** [comment]
Hi, thanks for pointing this out. I'll look at it later today.
